DROP USER IF EXISTS ''@'localhost', ''@'%';
DROP USER IF EXISTS 'root'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY '${ROOT_PASSWORD}';
DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE Db LIKE 'test\_%';
FLUSH PRIVILEGES;
