services:
  nginx:
    build:
      context: .
    image: nginx:hrazafia
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - type: bind
        source: ./html
        target: /var/www/html
      - type: bind
        source: ./ssl/hrazafia.42.fr
        target: /etc/ssl/hrazafia.42.fr
